from __future__ import annotations

from contextlib import contextmanager
from pathlib import Path
import re
from typing import Any, Iterator

from bookiebot.banking.crypto import TokenCipher
from bookiebot.banking.models import BankStatus
from bookiebot.banking.store import BankStore


def _import_psycopg():
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ModuleNotFoundError as exc:
        raise RuntimeError(
            "BANK_DATABASE_URL is set, but psycopg is not installed. "
            "Install requirements.txt before using Postgres bank storage."
        ) from exc
    return psycopg, dict_row


def _postgres_sql(sql: str) -> str:
    return re.sub(r"\?", "%s", sql)


class _PostgresConnection:
    def __init__(self, conn: Any):
        self.conn = conn

    def execute(self, sql: str, params: tuple[Any, ...] = ()):
        return self.conn.execute(_postgres_sql(sql), params)

    def executemany(self, sql: str, params_seq):
        with self.conn.cursor() as cursor:
            return cursor.executemany(_postgres_sql(sql), params_seq)


class PostgresBankStore(BankStore):
    def __init__(self, database_url: str, cipher: TokenCipher):
        super().__init__(path=Path("postgres"), cipher=cipher)
        self.database_url = database_url

    @contextmanager
    def connect(self) -> Iterator[_PostgresConnection]:
        psycopg, dict_row = _import_psycopg()
        conn = psycopg.connect(self.database_url, row_factory=dict_row)
        try:
            yield _PostgresConnection(conn)
            conn.commit()
        finally:
            conn.close()

    def initialize(self) -> None:
        with self.connect() as conn:
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS bank_items (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    owner_key TEXT NOT NULL,
                    provider TEXT NOT NULL,
                    item_id TEXT NOT NULL UNIQUE,
                    encrypted_access_token TEXT NOT NULL,
                    institution_name TEXT,
                    status TEXT NOT NULL DEFAULT 'active',
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    disconnected_at TEXT
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS bank_accounts (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    item_id INTEGER NOT NULL REFERENCES bank_items(id) ON DELETE CASCADE,
                    provider_account_id TEXT NOT NULL UNIQUE,
                    owner_key TEXT NOT NULL,
                    name TEXT NOT NULL,
                    mask TEXT,
                    type TEXT,
                    subtype TEXT,
                    official_name TEXT,
                    current_balance DOUBLE PRECISION,
                    available_balance DOUBLE PRECISION,
                    watched INTEGER NOT NULL DEFAULT 1,
                    updated_at TEXT NOT NULL
                )
                """
            )
            conn.execute("ALTER TABLE bank_accounts ADD COLUMN IF NOT EXISTS watched INTEGER NOT NULL DEFAULT 1")
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS bank_transactions (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    provider_transaction_id TEXT NOT NULL UNIQUE,
                    account_id INTEGER REFERENCES bank_accounts(id) ON DELETE SET NULL,
                    owner_key TEXT NOT NULL,
                    date TEXT,
                    authorized_date TEXT,
                    name TEXT NOT NULL,
                    merchant_name TEXT,
                    amount DOUBLE PRECISION NOT NULL,
                    pending INTEGER NOT NULL,
                    category TEXT,
                    payment_channel TEXT,
                    raw_json TEXT NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NOT NULL,
                    removed_at TEXT
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS bank_sync_state (
                    item_id INTEGER PRIMARY KEY REFERENCES bank_items(id) ON DELETE CASCADE,
                    transactions_cursor TEXT,
                    last_sync_at TEXT,
                    last_success_at TEXT,
                    last_error TEXT,
                    webhook_pending INTEGER NOT NULL DEFAULT 0
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS bank_reconciliation_items (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    owner_key TEXT NOT NULL,
                    bank_transaction_id INTEGER NOT NULL UNIQUE REFERENCES bank_transactions(id) ON DELETE CASCADE,
                    classification TEXT NOT NULL,
                    status TEXT NOT NULL,
                    matched_action_log_id TEXT,
                    matched_sheet_ref TEXT,
                    confidence DOUBLE PRECISION NOT NULL,
                    first_seen_at TEXT NOT NULL,
                    last_seen_at TEXT NOT NULL,
                    resolved_at TEXT,
                    ignored_at TEXT,
                    notes TEXT
                )
                """
            )
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS bank_user_settings (
                    actor_key TEXT PRIMARY KEY,
                    default_reconciliation_snooze TEXT,
                    reconciliation_snooze_until TEXT,
                    updated_at TEXT NOT NULL
                )
                """
            )

    def status(self, configured: bool, plaid_env: str) -> BankStatus:
        status = super().status(configured, plaid_env)
        return BankStatus(
            configured=status.configured,
            plaid_env=status.plaid_env,
            sqlite_path="postgres",
            item_count=status.item_count,
            account_count=status.account_count,
            transaction_count=status.transaction_count,
            last_success_at=status.last_success_at,
            last_error=status.last_error,
        )
