const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const vm = require('node:vm')
const {createRequire} = require('node:module')
const req = createRequire(path.resolve('web/expense-report/package.json'))
const React = req('react'), renderer = req('react-test-renderer'), ts = req('typescript')
globalThis.IS_REACT_ACT_ENVIRONMENT = true
const requests = [], timers = new Map(), workHistory = [], copied = []
let serial = 0, tree, owner = 'Brian', clipboardFailure = false, guides = 0
const source = ts.transpileModule(fs.readFileSync('web/expense-report/src/widget-settings.tsx', 'utf8'), {
  compilerOptions: {module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, jsx: ts.JsxEmit.ReactJSX},
}).outputText
const runtime = {exports: {}, URL, Date, Error, AbortController,
  window: {location: {origin: 'https://bookiebot.example'}, setTimeout: (fn,ms)=>{timers.set(++serial,{fn,ms});return serial}, clearTimeout: id=>timers.delete(id)},
  navigator: {clipboard: {writeText: async value=>{if(clipboardFailure)throw Error('Clipboard unavailable'); copied.push(value)}}},
  fetch: (url,options)=>new Promise((resolve,reject)=>requests.push({url,options,resolve,reject})),
  require: name => name.endsWith('.css') ? {} : name === './components/ui/motion' ? {
    CollapsibleContent: ({open,id,children})=>React.createElement('div', {id,'data-open':open},children),
  } : name === './app-work-guard' ? {useAppWorkStatus: value=>{workHistory.push(value);return value=>workHistory.push(value)}} : req(name),
}
vm.runInNewContext(source,runtime)
const component = ()=>React.createElement(runtime.exports.WidgetSettings, {ownerName:owner, defaultMode:'projected', onOpenGuide:()=>guides++})
const text = node=>typeof node==='string'||typeof node==='number'?String(node):Array.isArray(node)?node.map(text).join(''):node?.children?node.children.map(text).join(''):''
const rendered = ()=>text(tree.toJSON())
const button = label => tree.root.findAllByType('button').find(node=>text(node)===label)
const byAria = label=>tree.root.findByProps({'aria-label':label})
const click = async node=>{assert.ok(node,'Expected control'); assert.ok(!node.props.disabled,'Control must be enabled');await renderer.act(async()=>{node.props.onClick()})}
const change = async (node,value)=>renderer.act(async()=>node.props.onChange({target:{value}}))
const respond = async (request,data,status=200)=>renderer.act(async()=>request.resolve({ok:status>=200&&status<300,status,json:async()=>data}))
const flush = async ()=>renderer.act(async()=>{})
const base = connections=>({connections,scriptUrl:'/app/widgets/script',setupInstructionsUrl:'/app/widgets/help'})
const pending = (id='b1',label='Brian’s iPhone')=>({id,label,mode:'projected',status:'pending',createdAt:'2026-09-09T10:00:00Z',expiresAt:new Date(Date.now()+600000).toISOString(),lastUsedAt:null})
const active = (id='b1',label='Brian’s iPhone')=>({...pending(id,label),status:'active',expiresAt:'2030-09-09T10:00:00Z',lastUsedAt:'2026-09-09T10:05:00Z'})
const pairResponse = connection=>({...base([connection]),pairing:{id:connection.id,setupCode:'https://bookiebot.example/app/widgets/connect#bbw_pair_abcdefghijklmnopqrstuvwxyz0123456789',expiresAt:connection.expiresAt}})
const latestRequest = ()=>requests.at(-1)
const submit = async ()=>renderer.act(async()=>tree.root.findByType('form').props.onSubmit({preventDefault(){}}))
const lastWork = ()=>workHistory.at(-1)
;(async()=>{
  await renderer.act(async()=>{tree=renderer.create(component())})
  assert.equal(requests.length,1,'Mount reads settings without creating credentials')
  assert.equal(latestRequest().options.method,'GET')
  const fetchOptions = latestRequest().options
  assert.equal(fetchOptions.headers['X-BookieBot-App'],'1')
  for(const [key,value]of Object.entries({credentials:'same-origin',mode:'same-origin',referrerPolicy:'same-origin',cache:'no-store',redirect:'error'}))assert.equal(fetchOptions[key],value)
  await respond(latestRequest(),base([]))
  assert.match(rendered(),/No widgets paired yet/)
  assert.equal(lastWork().dirty,false)
  await click(button('Pair a widget'))
  assert.equal(lastWork().dirty,false,'Opening the untouched defaults does not trigger a discard prompt')
  const nameInput = ()=>tree.root.findAllByType('input').find(node=>!node.props.readOnly)
  await change(nameInput(),'Brian’s phone widget')
  assert.equal(lastWork().dirty,true,'An edited pairing form participates in the work guard')
  await renderer.act(async()=>{tree.root.findByType('form').props.onSubmit({preventDefault(){}});tree.root.findByType('form').props.onSubmit({preventDefault(){}})})
  assert.equal(requests.length,2,'Double submit creates one pairing request')
  assert.equal(lastWork().pending,true)
  assert.deepEqual(JSON.parse(latestRequest().options.body),{operation:'pair',label:'Brian’s phone widget',mode:'projected'})
  const b1=pending('b1','Brian’s phone widget')
  await respond(latestRequest(),pairResponse(b1))
  assert.equal(lastWork().pending,false)
  assert.equal(lastWork().dirty,true,'A setup code is held in memory and guarded until copied/finished')
  assert.equal(byAria('Widget setup code').props.readOnly,true)
  assert.equal(byAria('Widget setup code').props.autoComplete,'off')
  const beforeGuide=requests.length, setupCode=byAria('Widget setup code').props.value
  await click(button('Set up widget'))
  await click(button('Setup guide'))
  assert.equal(guides,2,'Guide uses in-app navigation rather than leaving Settings')
  assert.equal(requests.length,beforeGuide,'Opening help never creates or redeems a pairing')
  assert.equal(byAria('Widget setup code').props.value,setupCode,'Opening help preserves the in-memory setup secret')
  assert.equal(tree.root.findAllByType('a').find(node=>text(node)==='Open Scriptable').props.href,'scriptable:///','Opening Scriptable carries no credential')
  await click(button('Copy setup code'))
  assert.equal(copied.length,1)
  assert.match(rendered(),/Setup code copied/)
  clipboardFailure=true
  await click(button('Copy setup code'))
  assert.match(rendered(),/Select and copy/,'Clipboard failure retains a selectable fallback')
  clipboardFailure=false
  await click(byAria('Refresh widgets'))
  await respond(latestRequest(),base([active('b1',b1.label)]))
  assert.equal(tree.root.findAllByProps({'aria-label':'Widget setup code'}).length,0,'Redeemed setup secrets are cleared on a settings refresh')
  assert.equal(lastWork().dirty,false)
  assert.match(rendered(),/Widget connected/)
  await change(byAria(`Budget view for ${b1.label}`),'current')
  assert.deepEqual(JSON.parse(latestRequest().options.body),{operation:'mode',id:'b1',mode:'current'})
  assert.equal(byAria(`Budget view for ${b1.label}`).props.value,'projected','Mode is not represented as saved until the server confirms it')
  await respond(latestRequest(),base([{...active('b1',b1.label),mode:'current'}]))
  assert.equal(byAria(`Budget view for ${b1.label}`).props.value,'current')
  assert.match(rendered(),/when iOS next refreshes/)
  const beforeRevoke=requests.length
  await click(button('Remove'))
  assert.equal(requests.length,beforeRevoke,'Removal requires an explicit confirmation')
  await click(button('Keep widget'))
  assert.equal(requests.length,beforeRevoke)
  await click(button('Remove'))
  await click(button('Remove widget access'))
  assert.deepEqual(JSON.parse(latestRequest().options.body),{operation:'revoke',id:'b1'})
  await respond(latestRequest(),base([]))
  assert.match(rendered(),/Widget access removed/)
  await click(button('Pair a widget'))
  await submit()
  await renderer.act(async()=>latestRequest().reject(Error('Lost response')))
  assert.match(rendered(),/Couldn’t confirm pairing/)
  assert.equal(button('Pair a widget').props.disabled,true,'An uncertain create cannot be blindly repeated')
  assert.equal(lastWork().pending,false,'A failed credential operation does not trap the global work guard')
  await click(byAria('Refresh widgets'))
  const orphan=pending('orphan','Pending from lost response')
  await respond(latestRequest(),base([orphan]))
  assert.match(rendered(),/Pending from lost response/)
  await click(byAria('Refresh widgets'))
  await renderer.act(async()=>latestRequest().reject(Error('Offline')))
  assert.match(rendered(),/Pending from lost response/,'A failed refresh preserves the latest successful connection list')
  assert.match(rendered(),/Offline/)
  await click(button('Remove'))
  await click(button('Remove widget access'))
  await respond(latestRequest(),base([]))
  // Closing an explicit setup code releases the dirty guard without creating another grant.
  if(!button('Pair a widget').props['aria-expanded'])await click(button('Pair a widget'))
  await submit()
  await respond(latestRequest(),pairResponse(pending('expires')))
  const pairExpiry=[...timers.values()].find(timer=>timer.ms>20000)
  assert.ok(pairExpiry,'Pending setup gets an expiry timer')
  await renderer.act(async()=>pairExpiry.fn())
  assert.equal(tree.root.findAllByProps({'aria-label':'Widget setup code'}).length,0,'Expired pairing secrets disappear from the UI')
  assert.equal(lastWork().dirty,false)
  assert.match(rendered(),/setup code expired/)
  await click(byAria('Refresh widgets'))
  await respond(latestRequest(),base(Array.from({length:5},(_,i)=>active('limit'+i,'Phone '+i))))
  assert.equal(button('Pair a widget').props.disabled,true,'Server connection limit is reflected without hiding revocation controls')
  assert.match(rendered(),/Five widgets are paired/)
  await click(byAria('Refresh widgets'))
  await respond(latestRequest(),{...base([]),scriptUrl:'https://other.example/leak'})
  assert.match(rendered(),/Phone 0/,'Malformed settings never replace the last known safe list')
  assert.ok(button('Set up widget'),'Malformed links cannot replace the internal setup guide')
  await click(byAria('Refresh widgets'))
  await respond(latestRequest(),base([]))
  // A malformed or cross-origin setup response is never displayed or copied.
  if(!button('Pair a widget').props['aria-expanded'])await click(button('Pair a widget'))
  await submit()
  const tampered=pairResponse(pending())
  tampered.pairing.setupCode='https://other.example/app/widgets/connect#bbw_pair_abcdefghijklmnopqrstuvwxyz0123456789'
  await respond(latestRequest(),tampered)
  assert.equal(tree.root.findAllByProps({'aria-label':'Widget setup code'}).length,0)
  assert.match(rendered(),/Couldn’t confirm pairing/)
  await click(byAria('Refresh widgets'))
  await respond(latestRequest(),base([]))
  // Deadline releases a fetch that ignores AbortSignal; later completion stays ignored.
  await click(byAria('Refresh widgets'))
  const timedOut=latestRequest()
  await renderer.act(async()=>[...timers.values()].find(timer=>timer.ms===20000).fn())
  assert.equal(timedOut.options.signal.aborted,true)
  assert.equal(lastWork().pending,false)
  assert.match(rendered(),/took too long/)
  await respond(timedOut,base([active('late','Must not appear')]))
  assert.doesNotMatch(rendered(),/Must not appear/)
  // Changing the signed-in owner aborts old operations and discards all prior secrets/list state.
  await click(byAria('Refresh widgets'))
  const brianRequest=latestRequest()
  owner='Hannah'
  await renderer.act(async()=>tree.update(component()))
  assert.equal(brianRequest.options.signal.aborted,true)
  assert.doesNotMatch(rendered(),/Brian’s/)
  const hannahRequest=latestRequest()
  await respond(hannahRequest,base([active('h1','Hannah’s iPhone')]))
  await respond(brianRequest,base([active('b1','Brian old')]))
  assert.match(rendered(),/Hannah’s iPhone/)
  assert.doesNotMatch(rendered(),/Brian old/)
  // Unmount aborts an in-flight mutation and ignores the eventual response.
  await change(byAria('Budget view for Hannah’s iPhone'),'current')
  const afterUnmount=latestRequest()
  await renderer.act(async()=>tree.unmount())
  assert.equal(afterUnmount.options.signal.aborted,true)
  await respond(afterUnmount,base([]))
  assert.equal(timers.size,0)
  console.log('Widget settings lifecycle, pairing, revocation, mode, recovery, deadlines and owner isolation passed')
})().catch(error=>{console.error(error);process.exitCode=1})
